// Code generated by generator.py. DO NOT EDIT.

package types

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

type ClustersResourceModel struct {
	ID                  types.String  `tfsdk:"id"`
	ParentId            types.String  `tfsdk:"parent_id"`
	ClusterType         types.String  `tfsdk:"cluster_type"`
	OrgName             types.String  `tfsdk:"org_name"`
	EnvironmentName     types.String  `tfsdk:"environment_name"`
	Project             types.String  `tfsdk:"project"`
	Name                types.String  `tfsdk:"name"`
	Engine              types.String  `tfsdk:"engine"`
	Version             types.String  `tfsdk:"version"`
	TerminationPolicy   types.String  `tfsdk:"termination_policy"`
	Mode                types.String  `tfsdk:"mode"`
	Extra               types.Dynamic `tfsdk:"extra"`
	SingleZone          types.Bool    `tfsdk:"single_zone"`
	NodeGroup           types.String  `tfsdk:"node_group"`
	DisplayName         types.String  `tfsdk:"display_name"`
	Static              types.Bool    `tfsdk:"static"`
	NetworkMode         types.String  `tfsdk:"network_mode"`
	SchedulingPolicy    types.String  `tfsdk:"scheduling_policy"`
	AvailabilityZones   types.List    `tfsdk:"availability_zones"`
	ParamTpls           types.List    `tfsdk:"param_tpls"`
	Components          types.List    `tfsdk:"components"`
	InitOptions         types.List    `tfsdk:"init_options"`
	ServiceRefs         types.List    `tfsdk:"service_refs"`
	License             types.Object  `tfsdk:"license"`
	Backup              types.Object  `tfsdk:"backup"`
	ObjectStorageConfig types.Object  `tfsdk:"object_storage_config"`
	MaintainceWindow    types.Object  `tfsdk:"maintaince_window"`
}

func (m *ClustersResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["parentId"]; ok && val != nil {
		m.ParentId = types.StringValue(val.(string))
	} else {
		m.ParentId = types.StringNull()
	}
	if val, ok := apiData["clusterType"]; ok && val != nil {
		m.ClusterType = types.StringValue(val.(string))
	} else {
		m.ClusterType = types.StringNull()
	}
	if val, ok := apiData["orgName"]; ok && val != nil {
		m.OrgName = types.StringValue(val.(string))
	} else {
		m.OrgName = types.StringNull()
	}
	if val, ok := apiData["environmentName"]; ok && val != nil {
		m.EnvironmentName = types.StringValue(val.(string))
	} else {
		m.EnvironmentName = types.StringNull()
	}
	if val, ok := apiData["project"]; ok && val != nil {
		m.Project = types.StringValue(val.(string))
	} else {
		m.Project = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["engine"]; ok && val != nil {
		m.Engine = types.StringValue(val.(string))
	} else {
		m.Engine = types.StringNull()
	}
	if val, ok := apiData["version"]; ok && val != nil {
		m.Version = types.StringValue(val.(string))
	} else {
		m.Version = types.StringNull()
	}
	if val, ok := apiData["terminationPolicy"]; ok && val != nil {
		m.TerminationPolicy = types.StringValue(val.(string))
	} else {
		m.TerminationPolicy = types.StringNull()
	}
	if val, ok := apiData["mode"]; ok && val != nil {
		m.Mode = types.StringValue(val.(string))
	} else {
		m.Mode = types.StringNull()
	}
	if val, ok := apiData["extra"]; ok && val != nil {
		// Keep original value if it is valid, otherwise set null
		if m.Extra.IsUnknown() {
			m.Extra = basetypes.NewDynamicNull()
		}
	} else {
		if m.Extra.IsUnknown() {
			m.Extra = basetypes.NewDynamicNull()
		}
	}
	if val, ok := apiData["singleZone"]; ok && val != nil {
		m.SingleZone = types.BoolValue(val.(bool))
	} else {
		m.SingleZone = types.BoolNull()
	}
	if val, ok := apiData["nodeGroup"]; ok && val != nil {
		m.NodeGroup = types.StringValue(val.(string))
	} else {
		m.NodeGroup = types.StringNull()
	}
	if val, ok := apiData["displayName"]; ok && val != nil {
		m.DisplayName = types.StringValue(val.(string))
	} else {
		m.DisplayName = types.StringNull()
	}
	if val, ok := apiData["static"]; ok && val != nil {
		m.Static = types.BoolValue(val.(bool))
	} else {
		m.Static = types.BoolNull()
	}
	if val, ok := apiData["networkMode"]; ok && val != nil {
		m.NetworkMode = types.StringValue(val.(string))
	} else {
		m.NetworkMode = types.StringNull()
	}
	if val, ok := apiData["schedulingPolicy"]; ok && val != nil {
		m.SchedulingPolicy = types.StringValue(val.(string))
	} else {
		m.SchedulingPolicy = types.StringNull()
	}
	if val, ok := apiData["availabilityZones"]; ok && val != nil {
		var items []attr.Value
		for _, item := range val.([]interface{}) {
			items = append(items, types.StringValue(item.(string)))
		}
		list, d := types.ListValue(types.StringType, items)
		diags.Append(d...)
		m.AvailabilityZones = list
	} else {
		m.AvailabilityZones = types.ListNull(types.StringType)
	}
	if val, ok := apiData["license"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel LicenseResourceModel
		if !m.License.IsNull() && !m.License.IsUnknown() {
			m.License.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.License = obj
	} else {
		m.License = types.ObjectNull(LicenseResourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["backup"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel BackupResourceModel
		if !m.Backup.IsNull() && !m.Backup.IsUnknown() {
			m.Backup.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.Backup = obj
	} else {
		m.Backup = types.ObjectNull(BackupResourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["objectStorageConfig"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ObjectStorageConfigResourceModel
		if !m.ObjectStorageConfig.IsNull() && !m.ObjectStorageConfig.IsUnknown() {
			m.ObjectStorageConfig.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ObjectStorageConfig = obj
	} else {
		m.ObjectStorageConfig = types.ObjectNull(ObjectStorageConfigResourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["maintainceWindow"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel MaintainceWindowResourceModel
		if !m.MaintainceWindow.IsNull() && !m.MaintainceWindow.IsUnknown() {
			m.MaintainceWindow.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.MaintainceWindow = obj
	} else {
		m.MaintainceWindow = types.ObjectNull(MaintainceWindowResourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["paramTpls"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ParamTplsResourceModel
		if !m.ParamTpls.IsNull() && !m.ParamTpls.IsUnknown() {
			m.ParamTpls.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ParamTplsResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ParamTplsResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.ParamTpls = list
	} else {
		m.ParamTpls = types.ListNull(types.ObjectType{AttrTypes: ParamTplsResourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["components"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ComponentsResourceModel
		if !m.Components.IsNull() && !m.Components.IsUnknown() {
			m.Components.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ComponentsResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ComponentsResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Components = list
	} else {
		m.Components = types.ListNull(types.ObjectType{AttrTypes: ComponentsResourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["initOptions"]; ok && val != nil {
		var items []attr.Value
		var oldElements []InitOptionsResourceModel
		if !m.InitOptions.IsNull() && !m.InitOptions.IsUnknown() {
			m.InitOptions.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel InitOptionsResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: InitOptionsResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.InitOptions = list
	} else {
		m.InitOptions = types.ListNull(types.ObjectType{AttrTypes: InitOptionsResourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["serviceRefs"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ServiceRefsResourceModel
		if !m.ServiceRefs.IsNull() && !m.ServiceRefs.IsUnknown() {
			m.ServiceRefs.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ServiceRefsResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ServiceRefsResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.ServiceRefs = list
	} else {
		m.ServiceRefs = types.ListNull(types.ObjectType{AttrTypes: ServiceRefsResourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *ClustersResourceModel) Merge(remote *ClustersResourceModel) {
	if m.ParentId.IsNull() || m.ParentId.IsUnknown() {
		m.ParentId = remote.ParentId
	}
	if m.ClusterType.IsNull() || m.ClusterType.IsUnknown() {
		m.ClusterType = remote.ClusterType
	}
	if m.OrgName.IsNull() || m.OrgName.IsUnknown() {
		m.OrgName = remote.OrgName
	}
	if m.EnvironmentName.IsNull() || m.EnvironmentName.IsUnknown() {
		m.EnvironmentName = remote.EnvironmentName
	}
	if m.Project.IsNull() || m.Project.IsUnknown() {
		m.Project = remote.Project
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Engine.IsNull() || m.Engine.IsUnknown() {
		m.Engine = remote.Engine
	}
	if m.Version.IsNull() || m.Version.IsUnknown() {
		m.Version = remote.Version
	}
	if m.TerminationPolicy.IsNull() || m.TerminationPolicy.IsUnknown() {
		m.TerminationPolicy = remote.TerminationPolicy
	}
	if m.Mode.IsNull() || m.Mode.IsUnknown() {
		m.Mode = remote.Mode
	}
	if m.Extra.IsNull() || m.Extra.IsUnknown() {
		m.Extra = remote.Extra
	}
	if m.SingleZone.IsNull() || m.SingleZone.IsUnknown() {
		m.SingleZone = remote.SingleZone
	}
	if m.NodeGroup.IsNull() || m.NodeGroup.IsUnknown() {
		m.NodeGroup = remote.NodeGroup
	}
	if m.DisplayName.IsNull() || m.DisplayName.IsUnknown() {
		m.DisplayName = remote.DisplayName
	}
	if m.Static.IsNull() || m.Static.IsUnknown() {
		m.Static = remote.Static
	}
	if m.NetworkMode.IsNull() || m.NetworkMode.IsUnknown() {
		m.NetworkMode = remote.NetworkMode
	}
	if m.SchedulingPolicy.IsNull() || m.SchedulingPolicy.IsUnknown() {
		m.SchedulingPolicy = remote.SchedulingPolicy
	}
	if m.AvailabilityZones.IsNull() || m.AvailabilityZones.IsUnknown() {
		m.AvailabilityZones = remote.AvailabilityZones
	}
	if m.License.IsNull() || m.License.IsUnknown() {
		m.License = remote.License
	} else {
		var localObj LicenseResourceModel
		var remoteObj LicenseResourceModel
		if !m.License.IsNull() && !m.License.IsUnknown() {
			m.License.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.License.IsNull() && !remote.License.IsUnknown() {
			remote.License.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.License = obj
		}
	}
	if m.Backup.IsNull() || m.Backup.IsUnknown() {
		m.Backup = remote.Backup
	} else {
		var localObj BackupResourceModel
		var remoteObj BackupResourceModel
		if !m.Backup.IsNull() && !m.Backup.IsUnknown() {
			m.Backup.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.Backup.IsNull() && !remote.Backup.IsUnknown() {
			remote.Backup.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.Backup = obj
		}
	}
	if m.ObjectStorageConfig.IsNull() || m.ObjectStorageConfig.IsUnknown() {
		m.ObjectStorageConfig = remote.ObjectStorageConfig
	} else {
		var localObj ObjectStorageConfigResourceModel
		var remoteObj ObjectStorageConfigResourceModel
		if !m.ObjectStorageConfig.IsNull() && !m.ObjectStorageConfig.IsUnknown() {
			m.ObjectStorageConfig.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ObjectStorageConfig.IsNull() && !remote.ObjectStorageConfig.IsUnknown() {
			remote.ObjectStorageConfig.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ObjectStorageConfig = obj
		}
	}
	if m.MaintainceWindow.IsNull() || m.MaintainceWindow.IsUnknown() {
		m.MaintainceWindow = remote.MaintainceWindow
	} else {
		var localObj MaintainceWindowResourceModel
		var remoteObj MaintainceWindowResourceModel
		if !m.MaintainceWindow.IsNull() && !m.MaintainceWindow.IsUnknown() {
			m.MaintainceWindow.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.MaintainceWindow.IsNull() && !remote.MaintainceWindow.IsUnknown() {
			remote.MaintainceWindow.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.MaintainceWindow = obj
		}
	}
	if m.ParamTpls.IsNull() || m.ParamTpls.IsUnknown() {
		m.ParamTpls = remote.ParamTpls
	} else {
		var localList []ParamTplsResourceModel
		var remoteList []ParamTplsResourceModel
		if !m.ParamTpls.IsNull() && !m.ParamTpls.IsUnknown() {
			m.ParamTpls.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.ParamTpls.IsNull() && !remote.ParamTpls.IsUnknown() {
			remote.ParamTpls.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ParamTplsResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.ParamTpls = list
		}
	}
	if m.Components.IsNull() || m.Components.IsUnknown() {
		m.Components = remote.Components
	} else {
		var localList []ComponentsResourceModel
		var remoteList []ComponentsResourceModel
		if !m.Components.IsNull() && !m.Components.IsUnknown() {
			m.Components.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Components.IsNull() && !remote.Components.IsUnknown() {
			remote.Components.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ComponentsResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Components = list
		}
	}
	if m.InitOptions.IsNull() || m.InitOptions.IsUnknown() {
		m.InitOptions = remote.InitOptions
	} else {
		var localList []InitOptionsResourceModel
		var remoteList []InitOptionsResourceModel
		if !m.InitOptions.IsNull() && !m.InitOptions.IsUnknown() {
			m.InitOptions.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.InitOptions.IsNull() && !remote.InitOptions.IsUnknown() {
			remote.InitOptions.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: InitOptionsResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.InitOptions = list
		}
	}
	if m.ServiceRefs.IsNull() || m.ServiceRefs.IsUnknown() {
		m.ServiceRefs = remote.ServiceRefs
	} else {
		var localList []ServiceRefsResourceModel
		var remoteList []ServiceRefsResourceModel
		if !m.ServiceRefs.IsNull() && !m.ServiceRefs.IsUnknown() {
			m.ServiceRefs.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.ServiceRefs.IsNull() && !remote.ServiceRefs.IsUnknown() {
			remote.ServiceRefs.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ServiceRefsResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.ServiceRefs = list
		}
	}
}

type ParamTplsResourceModel struct {
	Component         types.String `tfsdk:"component"`
	ParamTplName      types.String `tfsdk:"param_tpl_name"`
	ParamTplId        types.String `tfsdk:"param_tpl_id"`
	OrgName           types.String `tfsdk:"org_name"`
	ParamTplPartition types.String `tfsdk:"param_tpl_partition"`
}

func (v ParamTplsResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"component":           types.StringType,
		"param_tpl_name":      types.StringType,
		"param_tpl_id":        types.StringType,
		"org_name":            types.StringType,
		"param_tpl_partition": types.StringType,
	}
}

func (m *ParamTplsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	// skip updating paramTplName
	// skip updating paramTplID
	if val, ok := apiData["orgName"]; ok && val != nil {
		m.OrgName = types.StringValue(val.(string))
	} else {
		m.OrgName = types.StringNull()
	}
	if val, ok := apiData["paramTplPartition"]; ok && val != nil {
		m.ParamTplPartition = types.StringValue(val.(string))
	} else {
		m.ParamTplPartition = types.StringNull()
	}

	return diags
}

func (m *ParamTplsResourceModel) Merge(remote *ParamTplsResourceModel) {
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.ParamTplName.IsNull() || m.ParamTplName.IsUnknown() {
		m.ParamTplName = remote.ParamTplName
	}
	if m.ParamTplId.IsNull() || m.ParamTplId.IsUnknown() {
		m.ParamTplId = remote.ParamTplId
	}
	if m.OrgName.IsNull() || m.OrgName.IsUnknown() {
		m.OrgName = remote.OrgName
	}
	if m.ParamTplPartition.IsNull() || m.ParamTplPartition.IsUnknown() {
		m.ParamTplPartition = remote.ParamTplPartition
	}
}

type ComponentsResourceModel struct {
	Component               types.String  `tfsdk:"component"`
	CompNum                 types.Int64   `tfsdk:"comp_num"`
	Replicas                types.Int64   `tfsdk:"replicas"`
	SkipResourceConstraints types.Bool    `tfsdk:"skip_resource_constraints"`
	ClassCode               types.String  `tfsdk:"class_code"`
	Cpu                     types.Float64 `tfsdk:"cpu"`
	Memory                  types.Float64 `tfsdk:"memory"`
	StorageClass            types.String  `tfsdk:"storage_class"`
	SystemAccountSecretName types.String  `tfsdk:"system_account_secret_name"`
	Volumes                 types.List    `tfsdk:"volumes"`
}

func (v ComponentsResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"component":                  types.StringType,
		"comp_num":                   types.Int64Type,
		"replicas":                   types.Int64Type,
		"skip_resource_constraints":  types.BoolType,
		"class_code":                 types.StringType,
		"cpu":                        types.Float64Type,
		"memory":                     types.Float64Type,
		"storage_class":              types.StringType,
		"system_account_secret_name": types.StringType,
		"volumes":                    types.ListType{ElemType: types.ObjectType{AttrTypes: VolumesResourceModel{}.AttributeTypes()}},
	}
}

func (m *ComponentsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	if val, ok := apiData["compNum"]; ok && val != nil {
		m.CompNum = types.Int64Value(int64(val.(float64)))
	} else {
		m.CompNum = types.Int64Null()
	}
	if val, ok := apiData["replicas"]; ok && val != nil {
		m.Replicas = types.Int64Value(int64(val.(float64)))
	} else {
		m.Replicas = types.Int64Null()
	}
	if val, ok := apiData["skipResourceConstraints"]; ok && val != nil {
		m.SkipResourceConstraints = types.BoolValue(val.(bool))
	} else {
		m.SkipResourceConstraints = types.BoolNull()
	}
	if val, ok := apiData["classCode"]; ok && val != nil {
		m.ClassCode = types.StringValue(val.(string))
	} else {
		m.ClassCode = types.StringNull()
	}
	if val, ok := apiData["cpu"]; ok && val != nil {
		m.Cpu = types.Float64Value(val.(float64))
	} else {
		m.Cpu = types.Float64Null()
	}
	if val, ok := apiData["memory"]; ok && val != nil {
		m.Memory = types.Float64Value(val.(float64))
	} else {
		m.Memory = types.Float64Null()
	}
	if val, ok := apiData["storageClass"]; ok && val != nil {
		m.StorageClass = types.StringValue(val.(string))
	} else {
		m.StorageClass = types.StringNull()
	}
	if val, ok := apiData["systemAccountSecretName"]; ok && val != nil {
		m.SystemAccountSecretName = types.StringValue(val.(string))
	} else {
		m.SystemAccountSecretName = types.StringNull()
	}
	if val, ok := apiData["volumes"]; ok && val != nil {
		var items []attr.Value
		var oldElements []VolumesResourceModel
		if !m.Volumes.IsNull() && !m.Volumes.IsUnknown() {
			m.Volumes.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel VolumesResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: VolumesResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Volumes = list
	} else {
		m.Volumes = types.ListNull(types.ObjectType{AttrTypes: VolumesResourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *ComponentsResourceModel) Merge(remote *ComponentsResourceModel) {
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.CompNum.IsNull() || m.CompNum.IsUnknown() {
		m.CompNum = remote.CompNum
	}
	if m.Replicas.IsNull() || m.Replicas.IsUnknown() {
		m.Replicas = remote.Replicas
	}
	if m.SkipResourceConstraints.IsNull() || m.SkipResourceConstraints.IsUnknown() {
		m.SkipResourceConstraints = remote.SkipResourceConstraints
	}
	if m.ClassCode.IsNull() || m.ClassCode.IsUnknown() {
		m.ClassCode = remote.ClassCode
	}
	if m.Cpu.IsNull() || m.Cpu.IsUnknown() {
		m.Cpu = remote.Cpu
	}
	if m.Memory.IsNull() || m.Memory.IsUnknown() {
		m.Memory = remote.Memory
	}
	if m.StorageClass.IsNull() || m.StorageClass.IsUnknown() {
		m.StorageClass = remote.StorageClass
	}
	if m.SystemAccountSecretName.IsNull() || m.SystemAccountSecretName.IsUnknown() {
		m.SystemAccountSecretName = remote.SystemAccountSecretName
	}
	if m.Volumes.IsNull() || m.Volumes.IsUnknown() {
		m.Volumes = remote.Volumes
	} else {
		var localList []VolumesResourceModel
		var remoteList []VolumesResourceModel
		if !m.Volumes.IsNull() && !m.Volumes.IsUnknown() {
			m.Volumes.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Volumes.IsNull() && !remote.Volumes.IsUnknown() {
			remote.Volumes.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: VolumesResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Volumes = list
		}
	}
}

type VolumesResourceModel struct {
	Name       types.String  `tfsdk:"name"`
	Storage    types.Float64 `tfsdk:"storage"`
	IoLimits   types.Object  `tfsdk:"io_limits"`
	IoReserves types.Object  `tfsdk:"io_reserves"`
}

func (v VolumesResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":        types.StringType,
		"storage":     types.Float64Type,
		"io_limits":   types.ObjectType{AttrTypes: IoLimitsResourceModel{}.AttributeTypes()},
		"io_reserves": types.ObjectType{AttrTypes: IoReservesResourceModel{}.AttributeTypes()},
	}
}

func (m *VolumesResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["storage"]; ok && val != nil {
		m.Storage = types.Float64Value(val.(float64))
	} else {
		m.Storage = types.Float64Null()
	}
	if val, ok := apiData["ioLimits"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel IoLimitsResourceModel
		if !m.IoLimits.IsNull() && !m.IoLimits.IsUnknown() {
			m.IoLimits.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.IoLimits = obj
	} else {
		m.IoLimits = types.ObjectNull(IoLimitsResourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["ioReserves"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel IoReservesResourceModel
		if !m.IoReserves.IsNull() && !m.IoReserves.IsUnknown() {
			m.IoReserves.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.IoReserves = obj
	} else {
		m.IoReserves = types.ObjectNull(IoReservesResourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *VolumesResourceModel) Merge(remote *VolumesResourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Storage.IsNull() || m.Storage.IsUnknown() {
		m.Storage = remote.Storage
	}
	if m.IoLimits.IsNull() || m.IoLimits.IsUnknown() {
		m.IoLimits = remote.IoLimits
	} else {
		var localObj IoLimitsResourceModel
		var remoteObj IoLimitsResourceModel
		if !m.IoLimits.IsNull() && !m.IoLimits.IsUnknown() {
			m.IoLimits.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.IoLimits.IsNull() && !remote.IoLimits.IsUnknown() {
			remote.IoLimits.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.IoLimits = obj
		}
	}
	if m.IoReserves.IsNull() || m.IoReserves.IsUnknown() {
		m.IoReserves = remote.IoReserves
	} else {
		var localObj IoReservesResourceModel
		var remoteObj IoReservesResourceModel
		if !m.IoReserves.IsNull() && !m.IoReserves.IsUnknown() {
			m.IoReserves.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.IoReserves.IsNull() && !remote.IoReserves.IsUnknown() {
			remote.IoReserves.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.IoReserves = obj
		}
	}
}

type IoLimitsResourceModel struct {
	ReadIops  types.Int64 `tfsdk:"read_iops"`
	WriteIops types.Int64 `tfsdk:"write_iops"`
	ReadBps   types.Int64 `tfsdk:"read_bps"`
	WriteBps  types.Int64 `tfsdk:"write_bps"`
}

func (v IoLimitsResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"read_iops":  types.Int64Type,
		"write_iops": types.Int64Type,
		"read_bps":   types.Int64Type,
		"write_bps":  types.Int64Type,
	}
}

func (m *IoLimitsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["readIOPS"]; ok && val != nil {
		m.ReadIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadIops = types.Int64Null()
	}
	if val, ok := apiData["writeIOPS"]; ok && val != nil {
		m.WriteIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteIops = types.Int64Null()
	}
	if val, ok := apiData["readBPS"]; ok && val != nil {
		m.ReadBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadBps = types.Int64Null()
	}
	if val, ok := apiData["writeBPS"]; ok && val != nil {
		m.WriteBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteBps = types.Int64Null()
	}

	return diags
}

func (m *IoLimitsResourceModel) Merge(remote *IoLimitsResourceModel) {
	if m.ReadIops.IsNull() || m.ReadIops.IsUnknown() {
		m.ReadIops = remote.ReadIops
	}
	if m.WriteIops.IsNull() || m.WriteIops.IsUnknown() {
		m.WriteIops = remote.WriteIops
	}
	if m.ReadBps.IsNull() || m.ReadBps.IsUnknown() {
		m.ReadBps = remote.ReadBps
	}
	if m.WriteBps.IsNull() || m.WriteBps.IsUnknown() {
		m.WriteBps = remote.WriteBps
	}
}

type IoReservesResourceModel struct {
	ReadIops  types.Int64 `tfsdk:"read_iops"`
	WriteIops types.Int64 `tfsdk:"write_iops"`
	ReadBps   types.Int64 `tfsdk:"read_bps"`
	WriteBps  types.Int64 `tfsdk:"write_bps"`
}

func (v IoReservesResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"read_iops":  types.Int64Type,
		"write_iops": types.Int64Type,
		"read_bps":   types.Int64Type,
		"write_bps":  types.Int64Type,
	}
}

func (m *IoReservesResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["readIOPS"]; ok && val != nil {
		m.ReadIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadIops = types.Int64Null()
	}
	if val, ok := apiData["writeIOPS"]; ok && val != nil {
		m.WriteIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteIops = types.Int64Null()
	}
	if val, ok := apiData["readBPS"]; ok && val != nil {
		m.ReadBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadBps = types.Int64Null()
	}
	if val, ok := apiData["writeBPS"]; ok && val != nil {
		m.WriteBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteBps = types.Int64Null()
	}

	return diags
}

func (m *IoReservesResourceModel) Merge(remote *IoReservesResourceModel) {
	if m.ReadIops.IsNull() || m.ReadIops.IsUnknown() {
		m.ReadIops = remote.ReadIops
	}
	if m.WriteIops.IsNull() || m.WriteIops.IsUnknown() {
		m.WriteIops = remote.WriteIops
	}
	if m.ReadBps.IsNull() || m.ReadBps.IsUnknown() {
		m.ReadBps = remote.ReadBps
	}
	if m.WriteBps.IsNull() || m.WriteBps.IsUnknown() {
		m.WriteBps = remote.WriteBps
	}
}

type InitOptionsResourceModel struct {
	Component      types.String `tfsdk:"component"`
	InitParams     types.Map    `tfsdk:"init_params"`
	SpecName       types.String `tfsdk:"spec_name"`
	ConfigFileName types.String `tfsdk:"config_file_name"`
}

func (v InitOptionsResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"component":        types.StringType,
		"init_params":      types.MapType{ElemType: types.StringType},
		"spec_name":        types.StringType,
		"config_file_name": types.StringType,
	}
}

func (m *InitOptionsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	if val, ok := apiData["initParams"]; ok && val != nil {
		mapValues := make(map[string]attr.Value)
		for k, v := range val.(map[string]interface{}) {
			mapValues[k] = types.StringValue(v.(string))
		}
		m.InitParams, _ = types.MapValue(types.StringType, mapValues)
	} else {
		m.InitParams = types.MapNull(types.StringType)
	}
	if val, ok := apiData["specName"]; ok && val != nil {
		m.SpecName = types.StringValue(val.(string))
	} else {
		m.SpecName = types.StringNull()
	}
	if val, ok := apiData["configFileName"]; ok && val != nil {
		m.ConfigFileName = types.StringValue(val.(string))
	} else {
		m.ConfigFileName = types.StringNull()
	}

	return diags
}

func (m *InitOptionsResourceModel) Merge(remote *InitOptionsResourceModel) {
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.InitParams.IsNull() || m.InitParams.IsUnknown() {
		m.InitParams = remote.InitParams
	}
	if m.SpecName.IsNull() || m.SpecName.IsUnknown() {
		m.SpecName = remote.SpecName
	}
	if m.ConfigFileName.IsNull() || m.ConfigFileName.IsUnknown() {
		m.ConfigFileName = remote.ConfigFileName
	}
}

type ServiceRefsResourceModel struct {
	Name              types.String `tfsdk:"name"`
	Cluster           types.String `tfsdk:"cluster"`
	ServiceDescriptor types.Object `tfsdk:"service_descriptor"`
}

func (v ServiceRefsResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":               types.StringType,
		"cluster":            types.StringType,
		"service_descriptor": types.ObjectType{AttrTypes: ServiceDescriptorResourceModel{}.AttributeTypes()},
	}
}

func (m *ServiceRefsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["cluster"]; ok && val != nil {
		m.Cluster = types.StringValue(val.(string))
	} else {
		m.Cluster = types.StringNull()
	}
	if val, ok := apiData["serviceDescriptor"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceDescriptorResourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceDescriptor = obj
	} else {
		m.ServiceDescriptor = types.ObjectNull(ServiceDescriptorResourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ServiceRefsResourceModel) Merge(remote *ServiceRefsResourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Cluster.IsNull() || m.Cluster.IsUnknown() {
		m.Cluster = remote.Cluster
	}
	if m.ServiceDescriptor.IsNull() || m.ServiceDescriptor.IsUnknown() {
		m.ServiceDescriptor = remote.ServiceDescriptor
	} else {
		var localObj ServiceDescriptorResourceModel
		var remoteObj ServiceDescriptorResourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceDescriptor.IsNull() && !remote.ServiceDescriptor.IsUnknown() {
			remote.ServiceDescriptor.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceDescriptor = obj
		}
	}
}

type ServiceDescriptorResourceModel struct {
	Host     types.String `tfsdk:"host"`
	Port     types.String `tfsdk:"port"`
	Endpoint types.String `tfsdk:"endpoint"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
}

func (v ServiceDescriptorResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"host":     types.StringType,
		"port":     types.StringType,
		"endpoint": types.StringType,
		"username": types.StringType,
		"password": types.StringType,
	}
}

func (m *ServiceDescriptorResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["host"]; ok && val != nil {
		m.Host = types.StringValue(val.(string))
	} else {
		m.Host = types.StringNull()
	}
	if val, ok := apiData["port"]; ok && val != nil {
		m.Port = types.StringValue(val.(string))
	} else {
		m.Port = types.StringNull()
	}
	if val, ok := apiData["endpoint"]; ok && val != nil {
		m.Endpoint = types.StringValue(val.(string))
	} else {
		m.Endpoint = types.StringNull()
	}
	if val, ok := apiData["username"]; ok && val != nil {
		m.Username = types.StringValue(val.(string))
	} else {
		m.Username = types.StringNull()
	}
	if val, ok := apiData["password"]; ok && val != nil {
		m.Password = types.StringValue(val.(string))
	} else {
		m.Password = types.StringNull()
	}

	return diags
}

func (m *ServiceDescriptorResourceModel) Merge(remote *ServiceDescriptorResourceModel) {
	if m.Host.IsNull() || m.Host.IsUnknown() {
		m.Host = remote.Host
	}
	if m.Port.IsNull() || m.Port.IsUnknown() {
		m.Port = remote.Port
	}
	if m.Endpoint.IsNull() || m.Endpoint.IsUnknown() {
		m.Endpoint = remote.Endpoint
	}
	if m.Username.IsNull() || m.Username.IsUnknown() {
		m.Username = remote.Username
	}
	if m.Password.IsNull() || m.Password.IsUnknown() {
		m.Password = remote.Password
	}
}

type LicenseResourceModel struct {
	Id        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	ExpiredAt types.String `tfsdk:"expired_at"`
	Key       types.String `tfsdk:"key"`
	Keys      types.Map    `tfsdk:"keys"`
}

func (v LicenseResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"id":         types.StringType,
		"name":       types.StringType,
		"expired_at": types.StringType,
		"key":        types.StringType,
		"keys":       types.MapType{ElemType: types.StringType},
	}
}

func (m *LicenseResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["id"]; ok && val != nil {
		m.Id = types.StringValue(val.(string))
	} else {
		m.Id = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["expiredAt"]; ok && val != nil {
		m.ExpiredAt = types.StringValue(val.(string))
	} else {
		m.ExpiredAt = types.StringNull()
	}
	if val, ok := apiData["key"]; ok && val != nil {
		m.Key = types.StringValue(val.(string))
	} else {
		m.Key = types.StringNull()
	}
	if val, ok := apiData["keys"]; ok && val != nil {
		mapValues := make(map[string]attr.Value)
		for k, v := range val.(map[string]interface{}) {
			mapValues[k] = types.StringValue(v.(string))
		}
		m.Keys, _ = types.MapValue(types.StringType, mapValues)
	} else {
		m.Keys = types.MapNull(types.StringType)
	}

	return diags
}

func (m *LicenseResourceModel) Merge(remote *LicenseResourceModel) {
	if m.Id.IsNull() || m.Id.IsUnknown() {
		m.Id = remote.Id
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.ExpiredAt.IsNull() || m.ExpiredAt.IsUnknown() {
		m.ExpiredAt = remote.ExpiredAt
	}
	if m.Key.IsNull() || m.Key.IsUnknown() {
		m.Key = remote.Key
	}
	if m.Keys.IsNull() || m.Keys.IsUnknown() {
		m.Keys = remote.Keys
	}
}

type BackupResourceModel struct {
	PitrEnabled               types.Bool   `tfsdk:"pitr_enabled"`
	ContinuousBackupMethod    types.String `tfsdk:"continuous_backup_method"`
	AutoBackup                types.Bool   `tfsdk:"auto_backup"`
	AutoBackupMethod          types.String `tfsdk:"auto_backup_method"`
	BackupRepo                types.String `tfsdk:"backup_repo"`
	CronExpression            types.String `tfsdk:"cron_expression"`
	RetentionPeriod           types.String `tfsdk:"retention_period"`
	RetentionPolicy           types.String `tfsdk:"retention_policy"`
	SnapshotVolumes           types.Bool   `tfsdk:"snapshot_volumes"`
	IncrementalBackupEnabled  types.Bool   `tfsdk:"incremental_backup_enabled"`
	IncrementalCronExpression types.String `tfsdk:"incremental_cron_expression"`
}

func (v BackupResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"pitr_enabled":                types.BoolType,
		"continuous_backup_method":    types.StringType,
		"auto_backup":                 types.BoolType,
		"auto_backup_method":          types.StringType,
		"backup_repo":                 types.StringType,
		"cron_expression":             types.StringType,
		"retention_period":            types.StringType,
		"retention_policy":            types.StringType,
		"snapshot_volumes":            types.BoolType,
		"incremental_backup_enabled":  types.BoolType,
		"incremental_cron_expression": types.StringType,
	}
}

func (m *BackupResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["pitrEnabled"]; ok && val != nil {
		m.PitrEnabled = types.BoolValue(val.(bool))
	} else {
		m.PitrEnabled = types.BoolNull()
	}
	if val, ok := apiData["continuousBackupMethod"]; ok && val != nil {
		m.ContinuousBackupMethod = types.StringValue(val.(string))
	} else {
		m.ContinuousBackupMethod = types.StringNull()
	}
	if val, ok := apiData["autoBackup"]; ok && val != nil {
		m.AutoBackup = types.BoolValue(val.(bool))
	} else {
		m.AutoBackup = types.BoolNull()
	}
	if val, ok := apiData["autoBackupMethod"]; ok && val != nil {
		m.AutoBackupMethod = types.StringValue(val.(string))
	} else {
		m.AutoBackupMethod = types.StringNull()
	}
	if val, ok := apiData["backupRepo"]; ok && val != nil {
		m.BackupRepo = types.StringValue(val.(string))
	} else {
		m.BackupRepo = types.StringNull()
	}
	if val, ok := apiData["cronExpression"]; ok && val != nil {
		m.CronExpression = types.StringValue(val.(string))
	} else {
		m.CronExpression = types.StringNull()
	}
	if val, ok := apiData["retentionPeriod"]; ok && val != nil {
		m.RetentionPeriod = types.StringValue(val.(string))
	} else {
		m.RetentionPeriod = types.StringNull()
	}
	if val, ok := apiData["retentionPolicy"]; ok && val != nil {
		m.RetentionPolicy = types.StringValue(val.(string))
	} else {
		m.RetentionPolicy = types.StringNull()
	}
	if val, ok := apiData["snapshotVolumes"]; ok && val != nil {
		m.SnapshotVolumes = types.BoolValue(val.(bool))
	} else {
		m.SnapshotVolumes = types.BoolNull()
	}
	if val, ok := apiData["incrementalBackupEnabled"]; ok && val != nil {
		m.IncrementalBackupEnabled = types.BoolValue(val.(bool))
	} else {
		m.IncrementalBackupEnabled = types.BoolNull()
	}
	if val, ok := apiData["incrementalCronExpression"]; ok && val != nil {
		m.IncrementalCronExpression = types.StringValue(val.(string))
	} else {
		m.IncrementalCronExpression = types.StringNull()
	}

	return diags
}

func (m *BackupResourceModel) Merge(remote *BackupResourceModel) {
	if m.PitrEnabled.IsNull() || m.PitrEnabled.IsUnknown() {
		m.PitrEnabled = remote.PitrEnabled
	}
	if m.ContinuousBackupMethod.IsNull() || m.ContinuousBackupMethod.IsUnknown() {
		m.ContinuousBackupMethod = remote.ContinuousBackupMethod
	}
	if m.AutoBackup.IsNull() || m.AutoBackup.IsUnknown() {
		m.AutoBackup = remote.AutoBackup
	}
	if m.AutoBackupMethod.IsNull() || m.AutoBackupMethod.IsUnknown() {
		m.AutoBackupMethod = remote.AutoBackupMethod
	}
	if m.BackupRepo.IsNull() || m.BackupRepo.IsUnknown() {
		m.BackupRepo = remote.BackupRepo
	}
	if m.CronExpression.IsNull() || m.CronExpression.IsUnknown() {
		m.CronExpression = remote.CronExpression
	}
	if m.RetentionPeriod.IsNull() || m.RetentionPeriod.IsUnknown() {
		m.RetentionPeriod = remote.RetentionPeriod
	}
	if m.RetentionPolicy.IsNull() || m.RetentionPolicy.IsUnknown() {
		m.RetentionPolicy = remote.RetentionPolicy
	}
	if m.SnapshotVolumes.IsNull() || m.SnapshotVolumes.IsUnknown() {
		m.SnapshotVolumes = remote.SnapshotVolumes
	}
	if m.IncrementalBackupEnabled.IsNull() || m.IncrementalBackupEnabled.IsUnknown() {
		m.IncrementalBackupEnabled = remote.IncrementalBackupEnabled
	}
	if m.IncrementalCronExpression.IsNull() || m.IncrementalCronExpression.IsUnknown() {
		m.IncrementalCronExpression = remote.IncrementalCronExpression
	}
}

type ObjectStorageConfigResourceModel struct {
	Bucket       types.String `tfsdk:"bucket"`
	UsePathStyle types.Bool   `tfsdk:"use_path_style"`
	Region       types.String `tfsdk:"region"`
	ServiceRef   types.Object `tfsdk:"service_ref"`
}

func (v ObjectStorageConfigResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"bucket":         types.StringType,
		"use_path_style": types.BoolType,
		"region":         types.StringType,
		"service_ref":    types.ObjectType{AttrTypes: ServiceRefResourceModel{}.AttributeTypes()},
	}
}

func (m *ObjectStorageConfigResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["bucket"]; ok && val != nil {
		m.Bucket = types.StringValue(val.(string))
	} else {
		m.Bucket = types.StringNull()
	}
	if val, ok := apiData["usePathStyle"]; ok && val != nil {
		m.UsePathStyle = types.BoolValue(val.(bool))
	} else {
		m.UsePathStyle = types.BoolNull()
	}
	if val, ok := apiData["region"]; ok && val != nil {
		m.Region = types.StringValue(val.(string))
	} else {
		m.Region = types.StringNull()
	}
	if val, ok := apiData["serviceRef"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceRefResourceModel
		if !m.ServiceRef.IsNull() && !m.ServiceRef.IsUnknown() {
			m.ServiceRef.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceRef = obj
	} else {
		m.ServiceRef = types.ObjectNull(ServiceRefResourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ObjectStorageConfigResourceModel) Merge(remote *ObjectStorageConfigResourceModel) {
	if m.Bucket.IsNull() || m.Bucket.IsUnknown() {
		m.Bucket = remote.Bucket
	}
	if m.UsePathStyle.IsNull() || m.UsePathStyle.IsUnknown() {
		m.UsePathStyle = remote.UsePathStyle
	}
	if m.Region.IsNull() || m.Region.IsUnknown() {
		m.Region = remote.Region
	}
	if m.ServiceRef.IsNull() || m.ServiceRef.IsUnknown() {
		m.ServiceRef = remote.ServiceRef
	} else {
		var localObj ServiceRefResourceModel
		var remoteObj ServiceRefResourceModel
		if !m.ServiceRef.IsNull() && !m.ServiceRef.IsUnknown() {
			m.ServiceRef.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceRef.IsNull() && !remote.ServiceRef.IsUnknown() {
			remote.ServiceRef.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceRef = obj
		}
	}
}

type ServiceRefResourceModel struct {
	Name              types.String `tfsdk:"name"`
	Cluster           types.String `tfsdk:"cluster"`
	ServiceDescriptor types.Object `tfsdk:"service_descriptor"`
}

func (v ServiceRefResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":               types.StringType,
		"cluster":            types.StringType,
		"service_descriptor": types.ObjectType{AttrTypes: ServiceDescriptorResourceModel{}.AttributeTypes()},
	}
}

func (m *ServiceRefResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["cluster"]; ok && val != nil {
		m.Cluster = types.StringValue(val.(string))
	} else {
		m.Cluster = types.StringNull()
	}
	if val, ok := apiData["serviceDescriptor"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceDescriptorResourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceDescriptor = obj
	} else {
		m.ServiceDescriptor = types.ObjectNull(ServiceDescriptorResourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ServiceRefResourceModel) Merge(remote *ServiceRefResourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Cluster.IsNull() || m.Cluster.IsUnknown() {
		m.Cluster = remote.Cluster
	}
	if m.ServiceDescriptor.IsNull() || m.ServiceDescriptor.IsUnknown() {
		m.ServiceDescriptor = remote.ServiceDescriptor
	} else {
		var localObj ServiceDescriptorResourceModel
		var remoteObj ServiceDescriptorResourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceDescriptor.IsNull() && !remote.ServiceDescriptor.IsUnknown() {
			remote.ServiceDescriptor.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceDescriptor = obj
		}
	}
}

type MaintainceWindowResourceModel struct {
	StartHour types.Int64  `tfsdk:"start_hour"`
	EndHour   types.Int64  `tfsdk:"end_hour"`
	Weekdays  types.String `tfsdk:"weekdays"`
}

func (v MaintainceWindowResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"start_hour": types.Int64Type,
		"end_hour":   types.Int64Type,
		"weekdays":   types.StringType,
	}
}

func (m *MaintainceWindowResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["startHour"]; ok && val != nil {
		m.StartHour = types.Int64Value(int64(val.(float64)))
	} else {
		m.StartHour = types.Int64Null()
	}
	if val, ok := apiData["endHour"]; ok && val != nil {
		m.EndHour = types.Int64Value(int64(val.(float64)))
	} else {
		m.EndHour = types.Int64Null()
	}
	if val, ok := apiData["weekdays"]; ok && val != nil {
		m.Weekdays = types.StringValue(val.(string))
	} else {
		m.Weekdays = types.StringNull()
	}

	return diags
}

func (m *MaintainceWindowResourceModel) Merge(remote *MaintainceWindowResourceModel) {
	if m.StartHour.IsNull() || m.StartHour.IsUnknown() {
		m.StartHour = remote.StartHour
	}
	if m.EndHour.IsNull() || m.EndHour.IsUnknown() {
		m.EndHour = remote.EndHour
	}
	if m.Weekdays.IsNull() || m.Weekdays.IsUnknown() {
		m.Weekdays = remote.Weekdays
	}
}
